#!/bin/bash

java -version

javac MultiPredicateTest.java

echo
echo "********** TESTING JDK **********"
echo

java MultiPredicateTest

echo
echo "********** TESTING Xalan **********"
echo

java -classpath xalan/impl/xalan-2.7.1.jar:xalan/impl/serializer-2.11.0.jar:. MultiPredicateTest
